# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/git/raspberry_car_controller

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/git/raspberry_car_controller

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/git/raspberry_car_controller/CMakeFiles /home/alex/git/raspberry_car_controller//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/git/raspberry_car_controller/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raspberry_car_controller

# Build rule for target.
raspberry_car_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raspberry_car_controller
.PHONY : raspberry_car_controller

# fast build rule for target.
raspberry_car_controller/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/build
.PHONY : raspberry_car_controller/fast

#=============================================================================
# Target rules for targets named raspberry_car_controller_autogen

# Build rule for target.
raspberry_car_controller_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raspberry_car_controller_autogen
.PHONY : raspberry_car_controller_autogen

# fast build rule for target.
raspberry_car_controller_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller_autogen.dir/build.make CMakeFiles/raspberry_car_controller_autogen.dir/build
.PHONY : raspberry_car_controller_autogen/fast

raspberry_car_controller_autogen/mocs_compilation.o: raspberry_car_controller_autogen/mocs_compilation.cpp.o

.PHONY : raspberry_car_controller_autogen/mocs_compilation.o

# target to build an object file
raspberry_car_controller_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/raspberry_car_controller_autogen/mocs_compilation.cpp.o
.PHONY : raspberry_car_controller_autogen/mocs_compilation.cpp.o

raspberry_car_controller_autogen/mocs_compilation.i: raspberry_car_controller_autogen/mocs_compilation.cpp.i

.PHONY : raspberry_car_controller_autogen/mocs_compilation.i

# target to preprocess a source file
raspberry_car_controller_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/raspberry_car_controller_autogen/mocs_compilation.cpp.i
.PHONY : raspberry_car_controller_autogen/mocs_compilation.cpp.i

raspberry_car_controller_autogen/mocs_compilation.s: raspberry_car_controller_autogen/mocs_compilation.cpp.s

.PHONY : raspberry_car_controller_autogen/mocs_compilation.s

# target to generate assembly for a file
raspberry_car_controller_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/raspberry_car_controller_autogen/mocs_compilation.cpp.s
.PHONY : raspberry_car_controller_autogen/mocs_compilation.cpp.s

src/core/cbit.o: src/core/cbit.cpp.o

.PHONY : src/core/cbit.o

# target to build an object file
src/core/cbit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/cbit.cpp.o
.PHONY : src/core/cbit.cpp.o

src/core/cbit.i: src/core/cbit.cpp.i

.PHONY : src/core/cbit.i

# target to preprocess a source file
src/core/cbit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/cbit.cpp.i
.PHONY : src/core/cbit.cpp.i

src/core/cbit.s: src/core/cbit.cpp.s

.PHONY : src/core/cbit.s

# target to generate assembly for a file
src/core/cbit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/cbit.cpp.s
.PHONY : src/core/cbit.cpp.s

src/core/data_interface.o: src/core/data_interface.cpp.o

.PHONY : src/core/data_interface.o

# target to build an object file
src/core/data_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/data_interface.cpp.o
.PHONY : src/core/data_interface.cpp.o

src/core/data_interface.i: src/core/data_interface.cpp.i

.PHONY : src/core/data_interface.i

# target to preprocess a source file
src/core/data_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/data_interface.cpp.i
.PHONY : src/core/data_interface.cpp.i

src/core/data_interface.s: src/core/data_interface.cpp.s

.PHONY : src/core/data_interface.s

# target to generate assembly for a file
src/core/data_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/data_interface.cpp.s
.PHONY : src/core/data_interface.cpp.s

src/core/joystick.o: src/core/joystick.cpp.o

.PHONY : src/core/joystick.o

# target to build an object file
src/core/joystick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/joystick.cpp.o
.PHONY : src/core/joystick.cpp.o

src/core/joystick.i: src/core/joystick.cpp.i

.PHONY : src/core/joystick.i

# target to preprocess a source file
src/core/joystick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/joystick.cpp.i
.PHONY : src/core/joystick.cpp.i

src/core/joystick.s: src/core/joystick.cpp.s

.PHONY : src/core/joystick.s

# target to generate assembly for a file
src/core/joystick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/joystick.cpp.s
.PHONY : src/core/joystick.cpp.s

src/core/keyboard_input.o: src/core/keyboard_input.cpp.o

.PHONY : src/core/keyboard_input.o

# target to build an object file
src/core/keyboard_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/keyboard_input.cpp.o
.PHONY : src/core/keyboard_input.cpp.o

src/core/keyboard_input.i: src/core/keyboard_input.cpp.i

.PHONY : src/core/keyboard_input.i

# target to preprocess a source file
src/core/keyboard_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/keyboard_input.cpp.i
.PHONY : src/core/keyboard_input.cpp.i

src/core/keyboard_input.s: src/core/keyboard_input.cpp.s

.PHONY : src/core/keyboard_input.s

# target to generate assembly for a file
src/core/keyboard_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/keyboard_input.cpp.s
.PHONY : src/core/keyboard_input.cpp.s

src/core/keymap.o: src/core/keymap.cpp.o

.PHONY : src/core/keymap.o

# target to build an object file
src/core/keymap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/keymap.cpp.o
.PHONY : src/core/keymap.cpp.o

src/core/keymap.i: src/core/keymap.cpp.i

.PHONY : src/core/keymap.i

# target to preprocess a source file
src/core/keymap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/keymap.cpp.i
.PHONY : src/core/keymap.cpp.i

src/core/keymap.s: src/core/keymap.cpp.s

.PHONY : src/core/keymap.s

# target to generate assembly for a file
src/core/keymap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/keymap.cpp.s
.PHONY : src/core/keymap.cpp.s

src/core/utils.o: src/core/utils.cpp.o

.PHONY : src/core/utils.o

# target to build an object file
src/core/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/utils.cpp.o
.PHONY : src/core/utils.cpp.o

src/core/utils.i: src/core/utils.cpp.i

.PHONY : src/core/utils.i

# target to preprocess a source file
src/core/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/utils.cpp.i
.PHONY : src/core/utils.cpp.i

src/core/utils.s: src/core/utils.cpp.s

.PHONY : src/core/utils.s

# target to generate assembly for a file
src/core/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/utils.cpp.s
.PHONY : src/core/utils.cpp.s

src/core/video_renderer.o: src/core/video_renderer.cpp.o

.PHONY : src/core/video_renderer.o

# target to build an object file
src/core/video_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/video_renderer.cpp.o
.PHONY : src/core/video_renderer.cpp.o

src/core/video_renderer.i: src/core/video_renderer.cpp.i

.PHONY : src/core/video_renderer.i

# target to preprocess a source file
src/core/video_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/video_renderer.cpp.i
.PHONY : src/core/video_renderer.cpp.i

src/core/video_renderer.s: src/core/video_renderer.cpp.s

.PHONY : src/core/video_renderer.s

# target to generate assembly for a file
src/core/video_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/video_renderer.cpp.s
.PHONY : src/core/video_renderer.cpp.s

src/core/widgets.o: src/core/widgets.cpp.o

.PHONY : src/core/widgets.o

# target to build an object file
src/core/widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/widgets.cpp.o
.PHONY : src/core/widgets.cpp.o

src/core/widgets.i: src/core/widgets.cpp.i

.PHONY : src/core/widgets.i

# target to preprocess a source file
src/core/widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/widgets.cpp.i
.PHONY : src/core/widgets.cpp.i

src/core/widgets.s: src/core/widgets.cpp.s

.PHONY : src/core/widgets.s

# target to generate assembly for a file
src/core/widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/core/widgets.cpp.s
.PHONY : src/core/widgets.cpp.s

src/main/main.o: src/main/main.cpp.o

.PHONY : src/main/main.o

# target to build an object file
src/main/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/main/main.cpp.o
.PHONY : src/main/main.cpp.o

src/main/main.i: src/main/main.cpp.i

.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/main/main.cpp.i
.PHONY : src/main/main.cpp.i

src/main/main.s: src/main/main.cpp.s

.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspberry_car_controller.dir/build.make CMakeFiles/raspberry_car_controller.dir/src/main/main.cpp.s
.PHONY : src/main/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... raspberry_car_controller_autogen"
	@echo "... raspberry_car_controller"
	@echo "... raspberry_car_controller_autogen/mocs_compilation.o"
	@echo "... raspberry_car_controller_autogen/mocs_compilation.i"
	@echo "... raspberry_car_controller_autogen/mocs_compilation.s"
	@echo "... src/core/cbit.o"
	@echo "... src/core/cbit.i"
	@echo "... src/core/cbit.s"
	@echo "... src/core/data_interface.o"
	@echo "... src/core/data_interface.i"
	@echo "... src/core/data_interface.s"
	@echo "... src/core/joystick.o"
	@echo "... src/core/joystick.i"
	@echo "... src/core/joystick.s"
	@echo "... src/core/keyboard_input.o"
	@echo "... src/core/keyboard_input.i"
	@echo "... src/core/keyboard_input.s"
	@echo "... src/core/keymap.o"
	@echo "... src/core/keymap.i"
	@echo "... src/core/keymap.s"
	@echo "... src/core/utils.o"
	@echo "... src/core/utils.i"
	@echo "... src/core/utils.s"
	@echo "... src/core/video_renderer.o"
	@echo "... src/core/video_renderer.i"
	@echo "... src/core/video_renderer.s"
	@echo "... src/core/widgets.o"
	@echo "... src/core/widgets.i"
	@echo "... src/core/widgets.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

